### ISSUE TITLE
A question about the code variables

### ISSUE THREAD

**Issue by tdtrung17693** [QuinAsura/LOCK#3]
Hello. 
I 'm sorry to bother you. Could I ask you about the purpose of pwm_{upper,lower} and omega_{upper,lower} !? I have read your code thoroughly but I still don't know what they are and the purposes of them.  Thank you in advance.

**Comment by QuinAsura** [comment]
Hello,
Pwm_upper and lower correspond to highest and least pwm that can given as input to the motor driver through the controller. All the parameters used in class bot are specific to the bot we constructed probably should have used macros. You can probably refer https://www.coursera.org/learn/mobile-robot for the differential drive model from which this is loosely based on.
